export const TEXT_CH = {
  pageNotFound: "页面未找到",
  pageNotFoundText: "看起来你迷路了。",
  takeMeHome: "带我回家",
  goBack: "返回",
  back: "返回",
  search: "搜索",
  confirm: "确认",
  image: "图片",
  email: "电子邮件",
  next: "下一步",
  reset: "重置",
  submit: "提交",
  cancel: "取消",
  yes: "是",
  no: "否",
  user: "用户",
  completed: "已完成",
  name: "名称",
  enterEmail: "输入电子邮件",
  selectCountry: "选择国家",
  selectCountryCode: "选择国家代码",
  enterContact: "输入联系电话",
  message: "信息",
  enterMessage: "输入信息",
  contactNo: "联系电话",
  country: "国家",
  countryCode: "国家代码",
  enterCompanyName: "输入公司名称",
  close: "关闭",
  clear: "清除",
  apply: "应用",
  confirm: "确认",
  select: "选择",
  aboutUs: "关于我们",
  contactUs: "联系我们",
  multiLang: "多语言应用",
  changeTheme: "更改主题",
  paraOne:
    "CHANGE Networks 是一家跨国 IT 公司，专注于网络和软件开发。该公司是 COMMANDO 网络设备的全球授权分销商，也是 Cisco、Juniper、Fortinet 和 Huawei 等主要网络品牌的领先独立经销商。它在全球范围内销售网络设备，并为其内部和合资企业开发软件。",
  paraTwo:
    "CHANGE Networks 与 COMMANDO Networks Inc., USA 建立了战略合作伙伴关系，该公司专注于交换机、路由器、无线、光网络和迷你 PC 领域的网络设备。该公司是全球采购 COMMANDO 网络设备的领导者，提供无与伦比的成本优势。",
  paraThree:
    "该公司提供全新、类新/二手和翻新网络设备，专注于 COMMANDO、Cisco、Juniper 和 Fortinet 品牌。它拥有高效快捷的供应链，库存超过 1000 万美元。交货时间更短，支持及时，响应速度更快。无论设备状况如何，公司只销售 100% 原装和正品，并提供标准的一年保修。公司在市场区分化方面做出更明智的投资组合选择，专注于具有市场竞争优势的产品。它提供更高的投资回报率 (ROI) 和更低的总拥有成本 (TCO)。公司提供最高水平的价值、技术专业知识、服务和产品供应，同时保持合理的预算。",
  paraFour:
    "公司在战略地区（如迪拜、印度、中国、香港和美国）设有办事处，提供灵活的业务合作方式。它为您的业务提供附加值和市场差异化。自 2010 年以来，公司一直深耕网络行业。",
  paraFive: "如果您从事网络行业，请不要错过与 CHANGE 的商业机会。",
  talkToUs: "联系我们",
  giveUsACall: "拨打 +97143523344 给我们打电话",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    " 阿尔萨布哈路 6 号单元，阿尔萨布哈酒店大厦，邮政信箱 #242361 迪拉，迪拜，阿联酋",
  sendEmail: "发送电子邮件",
  emailMessage: "直接联系我们的支持团队以获得快速响应",
  getInTouchWithuS: "与我们联系",
  getInTouchWithUsMessage: " 我们很乐意与您联系，为您的业务增值。",
  companyName: "公司名称",
  products: "产品",
  price: "价格",
  welcomeMessage: "欢迎来到 MultiLangApp",
  recommendedProducts: "推荐产品",
  productsList: "产品列表",
  productDescription: "这是一个示例产品描述。",
  product: "产品",
};
