export const TEXT_EN = {
  pageNotFound: "Page Not Found",
  pageNotFoundText: "Looks like you're Lost your way.",
  takeMeHome: "Take Me Home",
  goBack: "Go Back",
  back: "Back",
  search: "Search",
  confirm: "Confirm",
  image: "Image",
  email: "Email",
  next: "Next",
  reset: "Reset",
  submit: "Submit",
  cancel: "Cancel",
  yes: "Yes",
  no: "No",
  user: "User",
  completed: "Completed",
  name: "Name",
  enterEmail: "Enter Email",
  selectCountry: "Select Country",
  selectCountryCode: "Select Country Code",
  enterContact: "Enter Contact No.",
  message: "Message",
  enterMessage: "Enter Message",
  contactNo: "Contact No.",
  country: "Country",
  countryCode: "Country Code",
  enterCompanyName: "Enter Company Name",
  close: "Close",
  clear: "Clear",
  apply: "Apply",
  confirm: "Confirm",
  select: "Select",
  aboutUs: "About Us",
  contactUs: "Contact us",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Change theme",
  paraOne:
    "CHANGE Networks is a multinational IT company with expertise in networking and software development. The company is an authorized Global Distributor of COMMANDO networking equipment and a leading independent reseller of major networking brands such as Cisco, Juniper, Fortinet and Huawei. It sells networking gear worldwide and develops software for its inhouse and joint venture requirements.",
  paraTwo:
    "CHANGE Networks has established strategic partnership with COMMANDO Networks Inc., USA – that offers networking equipment with expertise on Switches, Routers, Wireless, Optical Networking and Mini PCs. The company is powerhouse of sourcing COMMANDO networking equipment at cost that’s unmatched worldwide.",
  paraThree:
    "The company offers new, like new / pre-owned and refurbished networking equipment – with expertise in COMMANDO, Cisco, Juniper and Fortinet. It maintains efficient, faster supply chain and more than $10m in stock. The lead time is shorter, support is prompt, and the response time is faster. It only deals in 100% original and genuine products irrespective of the condition with standard one year warranty. The company makes sharper portfolio choices with focus on offerings with market differentiation and where it has strong and clear advantage. The company offers higher ROI and lower TCO. It offers the highest level of value, technical expertise, service, and product availability without breaking the budget.",
  paraFour:
    "The company offers flexibility in doing business with its presence in strategic geographies such as Dubai, India, China, Hong Kong, and USA. It adds value and market differentiation in your business offerings. The company has been deep in the networking business since 2010.",
  paraFive:
    "If you’re into networking, don't miss exploring business opportunities with CHANGE.",
  talkToUs: "Talk to Us",
  giveUsACall: "Give us a call on +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "  Al Sabkha Road, Unit No. 6, Al Sabkha Hotel Building, PO Box #242361 Deira, Dubai, UAE",
  sendEmail: "Send Email",
  emailMessage: "Directly contact our support team to get quick response",
  getInTouchWithuS: "Get In Touch With Us",
  getInTouchWithUsMessage:
    " We will be pleased to contact you to add value to your business.",
  companyName: "Company Name",

  //
  products: "Products",
  price: "Price",
  welcomeMessage: "Welcome to MultiLangApp",
  recommendedProducts: "Recommended Products",
  productsList: "Products List",
  productDescription: "This is a sample product description.",
  product: "Product",
};
