export const TEXT_ES = {
  pageNotFound: "Página no encontrada",
  pageNotFoundText: "Parece que te has perdido.",
  takeMeHome: "Llévame a casa",
  goBack: "Regresar",
  back: "Atrás",
  search: "Buscar",
  confirm: "Confirmar",
  image: "Imagen",
  email: "Correo electrónico",
  next: "Siguiente",
  reset: "Restablecer",
  submit: "Enviar",
  cancel: "Cancelar",
  yes: "Sí",
  no: "No",
  user: "Usuario",
  completed: "Completado",
  name: "Nombre",
  enterEmail: "Ingrese correo electrónico",
  selectCountry: "Seleccionar país",
  selectCountryCode: "Seleccionar código de país",
  enterContact: "Ingrese número de contacto",
  message: "Mensaje",
  enterMessage: "Ingrese mensaje",
  contactNo: "Número de contacto",
  country: "País",
  countryCode: "Código de país",
  enterCompanyName: "Ingrese nombre de la empresa",
  close: "Cerrar",
  clear: "Borrar",
  apply: "Aplicar",
  confirm: "Confirmar",
  select: "Seleccionar",
  aboutUs: "Sobre nosotros",
  contactUs: "Contáctenos",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Cambiar tema",
  paraOne:
    "CHANGE Networks es una empresa multinacional de TI con experiencia en redes y desarrollo de software. La empresa es un distribuidor global autorizado de equipos de redes COMMANDO y un revendedor independiente líder de marcas de redes importantes como Cisco, Juniper, Fortinet y Huawei. Vende equipos de redes en todo el mundo y desarrolla software para sus necesidades internas y de empresas conjuntas.",
  paraTwo:
    "CHANGE Networks ha establecido una asociación estratégica con COMMANDO Networks Inc., EE. UU., que ofrece equipos de redes con experiencia en conmutadores, enrutadores, redes inalámbricas, redes ópticas y mini PC. La empresa es una potencia en el suministro de equipos de redes COMMANDO a un costo inigualable en todo el mundo.",
  paraThree:
    "La empresa ofrece equipos de redes nuevos, como nuevos / de segunda mano y reacondicionados, con experiencia en COMMANDO, Cisco, Juniper y Fortinet. Mantiene una cadena de suministro eficiente y rápida con más de $10 millones en stock. El tiempo de entrega es más corto, el soporte es inmediato y el tiempo de respuesta es más rápido. Solo maneja productos 100% originales y genuinos, sin importar la condición, con una garantía estándar de un año. La empresa toma decisiones estratégicas con un enfoque en ofertas con diferenciación en el mercado y donde tiene una ventaja clara y fuerte. La empresa ofrece un mayor retorno de inversión (ROI) y un menor costo total de propiedad (TCO). Proporciona el más alto nivel de valor, experiencia técnica, servicio y disponibilidad de productos sin exceder el presupuesto.",
  paraFour:
    "La empresa ofrece flexibilidad en los negocios con su presencia en geografías estratégicas como Dubái, India, China, Hong Kong y EE. UU. Agrega valor y diferenciación en el mercado a sus ofertas comerciales. La empresa ha estado profundamente involucrada en el negocio de redes desde 2010.",
  paraFive:
    "Si estás en el negocio de redes, no te pierdas la oportunidad de explorar negocios con CHANGE.",
  talkToUs: "Habla con nosotros",
  giveUsACall: "Llámanos al +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "Al Sabkha Road, Unidad No. 6, Edificio del Hotel Al Sabkha, PO Box #242361 Deira, Dubái, EAU",
  sendEmail: "Enviar correo electrónico",
  emailMessage:
    "Contacta directamente con nuestro equipo de soporte para obtener una respuesta rápida",
  getInTouchWithuS: "Ponte en contacto con nosotros",
  getInTouchWithUsMessage:
    "Estaremos encantados de contactarte para agregar valor a tu negocio.",
  companyName: "Nombre de la empresa",
  products: "Productos",
  price: "Precio",
  welcomeMessage: "Bienvenido a MultiLangApp",
  recommendedProducts: "Productos Recomendados",
  productsList: "Lista de Productos",
  productDescription: "Esta es una descripción de producto de muestra.",
  product: "Producto",
};
