export const TEXT_FR = {
  pageNotFound: "Page non trouvée",
  pageNotFoundText: "On dirait que vous vous êtes perdu.",
  takeMeHome: "Ramenez-moi à la maison",
  goBack: "Retourner",
  back: "Retour",
  search: "Rechercher",
  confirm: "Confirmer",
  image: "Image",
  email: "E-mail",
  next: "Suivant",
  reset: "Réinitialiser",
  submit: "Soumettre",
  cancel: "Annuler",
  yes: "Oui",
  no: "Non",
  user: "Utilisateur",
  completed: "Terminé",
  name: "Nom",
  enterEmail: "Entrez l'e-mail",
  selectCountry: "Sélectionner un pays",
  selectCountryCode: "Sélectionner le code du pays",
  enterContact: "Entrez le numéro de contact",
  message: "Message",
  enterMessage: "Entrez le message",
  contactNo: "Numéro de contact",
  country: "Pays",
  countryCode: "Code du pays",
  enterCompanyName: "Entrez le nom de l'entreprise",
  close: "Fermer",
  clear: "Effacer",
  apply: "Appliquer",
  confirm: "Confirmer",
  select: "Sélectionner",
  aboutUs: "À propos de nous",
  contactUs: "Contactez-nous",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Changer de thème",
  paraOne:
    "CHANGE Networks est une entreprise informatique multinationale spécialisée dans les réseaux et le développement de logiciels. L'entreprise est un distributeur mondial agréé des équipements réseau COMMANDO et un revendeur indépendant majeur de grandes marques de réseaux telles que Cisco, Juniper, Fortinet et Huawei. Elle vend du matériel réseau dans le monde entier et développe des logiciels pour ses besoins internes et en coentreprise.",
  paraTwo:
    "CHANGE Networks a établi un partenariat stratégique avec COMMANDO Networks Inc., USA – qui propose des équipements réseau avec une expertise sur les commutateurs, routeurs, réseaux sans fil, réseaux optiques et mini-PC. L'entreprise est une source incontournable pour l'approvisionnement en équipements réseau COMMANDO à des prix imbattables dans le monde entier.",
  paraThree:
    "L'entreprise propose du matériel réseau neuf, comme neuf / d'occasion et remis à neuf – avec une expertise sur COMMANDO, Cisco, Juniper et Fortinet. Elle maintient une chaîne d'approvisionnement efficace et rapide avec plus de 10 millions de dollars de stock. Le délai de livraison est plus court, le support est rapide et le temps de réponse est plus rapide. Elle ne traite que des produits 100% originaux et authentiques, quelle que soit leur condition, avec une garantie standard d'un an. L'entreprise fait des choix de portefeuille plus avisés en mettant l'accent sur des offres différenciées sur le marché et où elle possède un avantage fort et clair. Elle offre un retour sur investissement plus élevé et un coût total de possession plus bas. Elle propose le plus haut niveau de valeur, d'expertise technique, de service et de disponibilité des produits sans dépasser le budget.",
  paraFour:
    "L'entreprise offre une flexibilité commerciale grâce à sa présence dans des zones stratégiques telles que Dubaï, l'Inde, la Chine, Hong Kong et les États-Unis. Elle ajoute de la valeur et une différenciation sur le marché à vos offres commerciales. Elle est profondément impliquée dans le secteur des réseaux depuis 2010.",
  paraFive:
    "Si vous travaillez dans le domaine des réseaux, ne manquez pas d'explorer les opportunités commerciales avec CHANGE.",
  talkToUs: "Parlez-nous",
  giveUsACall: "Appelez-nous au +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "  Al Sabkha Road, Unité No. 6, Al Sabkha Hotel Building, BO Box #242361 Deira, Dubaï, EAU",
  sendEmail: "Envoyer un e-mail",
  emailMessage:
    "Contactez directement notre équipe de support pour une réponse rapide",
  getInTouchWithuS: "Prenez contact avec nous",
  getInTouchWithUsMessage:
    "Nous serons ravis de vous contacter pour apporter de la valeur à votre entreprise.",
  companyName: "Nom de l'entreprise",
  products: "Produits",
  price: "Prix",
  welcomeMessage: "Bienvenue sur MultiLangApp",
  recommendedProducts: "Produits Recommandés",
  productsList: "Liste des Produits",
  productDescription: "Ceci est une description de produit d'exemple.",
  product: "Produit",
};
