export const TEXT_DE = {
  pageNotFound: "Seite nicht gefunden",
  pageNotFoundText: "Sieht so aus, als hätten Sie sich verirrt.",
  takeMeHome: "Bring mich nach Hause",
  goBack: "Geh zurück",
  back: "Zurück",
  search: "Suche",
  confirm: "Bestätigen",
  image: "Bild",
  email: "E-Mail",
  next: "Weiter",
  reset: "Zurücksetzen",
  submit: "Einreichen",
  cancel: "Abbrechen",
  yes: "Ja",
  no: "Nein",
  user: "Benutzer",
  completed: "Abgeschlossen",
  name: "Name",
  enterEmail: "E-Mail eingeben",
  selectCountry: "Land auswählen",
  selectCountryCode: "Ländercode auswählen",
  enterContact: "Kontakt Nr. eingeben",
  message: "Nachricht",
  enterMessage: "Nachricht eingeben",
  contactNo: "Kontakt Nr.",
  country: "Land",
  countryCode: "Ländercode",
  enterCompanyName: "Firmennamen eingeben",
  close: "Schließen",
  clear: "Löschen",
  apply: "Anwenden",
  confirm: "Bestätigen",
  select: "Auswählen",
  aboutUs: "Über uns",
  contactUs: "Kontaktieren Sie uns",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Thema ändern",
  paraOne:
    "CHANGE Networks ist ein multinationales IT-Unternehmen mit Expertise in Netzwerktechnik und Softwareentwicklung. Das Unternehmen ist ein autorisierter globaler Vertriebspartner von COMMANDO-Netzwerkausrüstung und ein führender unabhängiger Wiederverkäufer großer Netzwerkmarken wie Cisco, Juniper, Fortinet und Huawei. Es verkauft Netzwerkausrüstung weltweit und entwickelt Software für eigene und Joint-Venture-Anforderungen.",
  paraTwo:
    "CHANGE Networks hat eine strategische Partnerschaft mit COMMANDO Networks Inc., USA – einem Unternehmen, das Netzwerkausrüstung mit Schwerpunkt auf Switches, Router, Wireless, optische Netzwerke und Mini-PCs anbietet. Das Unternehmen ist eine Quelle für COMMANDO-Netzwerkausrüstung zu einem Preis, der weltweit unübertroffen ist.",
  paraThree:
    "Das Unternehmen bietet neue, neuwertige/gebrauchte und generalüberholte Netzwerkausrüstung mit Expertise in COMMANDO, Cisco, Juniper und Fortinet. Es unterhält eine effiziente, schnelle Lieferkette und verfügt über mehr als 10 Millionen US-Dollar an Lagerbeständen. Die Lieferzeit ist kürzer, der Support ist schnell und die Reaktionszeit ist schneller. Es handelt ausschließlich mit 100% originalen und authentischen Produkten, unabhängig vom Zustand, mit einer Standardgarantie von einem Jahr. Das Unternehmen trifft schärfere Portfolioentscheidungen mit Fokus auf Angebote mit Marktdifferenzierung und starkem Vorteil. Es bietet eine höhere Kapitalrendite und niedrigere Gesamtbetriebskosten. Es bietet das höchste Maß an Wert, technischer Expertise, Service und Produktverfügbarkeit ohne das Budget zu sprengen.",
  paraFour:
    "Das Unternehmen bietet Flexibilität im Geschäftsverkehr mit seiner Präsenz in strategischen Regionen wie Dubai, Indien, China, Hongkong und den USA. Es bringt Mehrwert und Marktdifferenzierung in Ihr Geschäftsangebot. Das Unternehmen ist seit 2010 tief im Netzwerkgeschäft tätig.",
  paraFive:
    "Wenn Sie in der Netzwerktechnik tätig sind, sollten Sie die Geschäftsmöglichkeiten mit CHANGE nicht verpassen.",
  talkToUs: "Sprechen Sie mit uns",
  giveUsACall: "Rufen Sie uns an unter +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "Al Sabkha Road, Einheit Nr. 6, Al Sabkha Hotel Building, Postfach #242361 Deira, Dubai, VAE",
  sendEmail: "E-Mail senden",
  emailMessage:
    "Kontaktieren Sie direkt unser Support-Team, um eine schnelle Antwort zu erhalten",
  getInTouchWithuS: "Nehmen Sie Kontakt mit uns auf",
  getInTouchWithUsMessage:
    "Wir freuen uns, Sie zu kontaktieren, um Ihrem Unternehmen Mehrwert zu bieten.",
  companyName: "Firmenname",
  products: "Produkte",
  price: "Preis",
  welcomeMessage: "Willkommen bei MultiLangApp",
  recommendedProducts: "Empfohlene Produkte",
  productsList: "Produktliste",
  productDescription: "Dies ist eine Beispielproduktbeschreibung.",
  product: "Produkt",
};
