export const TEXT_IT = {
  pageNotFound: "Pagina non trovata",
  pageNotFoundText: "Sembra che ti sia perso.",
  takeMeHome: "Portami a casa",
  goBack: "Torna indietro",
  back: "Indietro",
  search: "Cerca",
  confirm: "Conferma",
  image: "Immagine",
  email: "Email",
  next: "Avanti",
  reset: "Reimposta",
  submit: "Invia",
  cancel: "Annulla",
  yes: "Sì",
  no: "No",
  user: "Utente",
  completed: "Completato",
  name: "Nome",
  enterEmail: "Inserisci email",
  selectCountry: "Seleziona paese",
  selectCountryCode: "Seleziona prefisso internazionale",
  enterContact: "Inserisci numero di contatto",
  message: "Messaggio",
  enterMessage: "Inserisci messaggio",
  contactNo: "Numero di contatto",
  country: "Paese",
  countryCode: "Prefisso internazionale",
  enterCompanyName: "Inserisci il nome dell'azienda",
  close: "Chiudi",
  clear: "Cancella",
  apply: "Applica",
  confirm: "Conferma",
  select: "Seleziona",
  aboutUs: "Chi siamo",
  contactUs: "Contattaci",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Cambia tema",
  paraOne:
    "CHANGE Networks è un'azienda IT multinazionale con esperienza nel networking e nello sviluppo software. L'azienda è un distributore globale autorizzato di apparecchiature di rete COMMANDO e un rivenditore indipendente leader di marchi di networking come Cisco, Juniper, Fortinet e Huawei. Vende apparecchiature di rete in tutto il mondo e sviluppa software per esigenze interne e di joint venture.",
  paraTwo:
    "CHANGE Networks ha stabilito una partnership strategica con COMMANDO Networks Inc., USA – che offre apparecchiature di rete con esperienza su switch, router, reti wireless, reti ottiche e mini PC. L'azienda è una potenza nell'approvvigionamento di apparecchiature di rete COMMANDO a un costo imbattibile a livello mondiale.",
  paraThree:
    "L'azienda offre apparecchiature di rete nuove, come nuove/usate e ricondizionate – con esperienza in COMMANDO, Cisco, Juniper e Fortinet. Mantiene una catena di fornitura efficiente e veloce con oltre 10 milioni di dollari di scorte. I tempi di consegna sono più brevi, il supporto è tempestivo e i tempi di risposta sono rapidi. Si occupa esclusivamente di prodotti originali e genuini al 100%, indipendentemente dalle condizioni, con una garanzia standard di un anno. L'azienda effettua scelte di portafoglio più mirate, concentrandosi su offerte con differenziazione di mercato e vantaggi competitivi chiari. Offre un ROI più elevato e un TCO inferiore. Garantisce il massimo valore, competenza tecnica, servizio e disponibilità di prodotto senza sforare il budget.",
  paraFour:
    "L'azienda offre flessibilità negli affari grazie alla sua presenza in aree geografiche strategiche come Dubai, India, Cina, Hong Kong e USA. Aggiunge valore e differenziazione di mercato alle vostre offerte commerciali. È nel settore del networking dal 2010.",
  paraFive:
    "Se ti occupi di networking, non perdere l'opportunità di esplorare affari con CHANGE.",
  talkToUs: "Parla con noi",
  giveUsACall: "Chiamaci al +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "Al Sabkha Road, Unità n. 6, Edificio dell'Hotel Al Sabkha, Casella postale #242361 Deira, Dubai, Emirati Arabi Uniti",
  sendEmail: "Invia Email",
  emailMessage:
    "Contatta direttamente il nostro team di supporto per una risposta rapida",
  getInTouchWithuS: "Mettiti in contatto con noi",
  getInTouchWithUsMessage:
    "Saremo lieti di contattarti per aggiungere valore alla tua attività.",
  companyName: "Nome dell'azienda",
  products: "Prodotti",
  price: "Prezzo",
  welcomeMessage: "Benvenuto su MultiLangApp",
  recommendedProducts: "Prodotti consigliati",
  productsList: "Elenco prodotti",
  productDescription: "Questa è una descrizione di prodotto di esempio.",
  product: "Prodotto",
};
