export const TEXT_JP = {
  pageNotFound: "ページが見つかりません",
  pageNotFoundText: "道に迷ったようです。",
  takeMeHome: "ホームへ戻る",
  goBack: "戻る",
  back: "戻る",
  search: "検索",
  confirm: "確認",
  image: "画像",
  email: "メール",
  next: "次へ",
  reset: "リセット",
  submit: "送信",
  cancel: "キャンセル",
  yes: "はい",
  no: "いいえ",
  user: "ユーザー",
  completed: "完了",
  name: "名前",
  enterEmail: "メールアドレスを入力",
  selectCountry: "国を選択",
  selectCountryCode: "国コードを選択",
  enterContact: "連絡先番号を入力",
  message: "メッセージ",
  enterMessage: "メッセージを入力",
  contactNo: "連絡先番号",
  country: "国",
  countryCode: "国コード",
  enterCompanyName: "会社名を入力",
  close: "閉じる",
  clear: "クリア",
  apply: "適用",
  confirm: "確認",
  select: "選択",
  aboutUs: "私たちについて",
  contactUs: "お問い合わせ",
  multiLang: "マルチランゲージアプリ",
  changeTheme: "テーマを変更",
  paraOne:
    "CHANGE Networksは、ネットワーキングおよびソフトウェア開発の専門知識を持つ多国籍IT企業です。同社はCOMMANDOネットワーク機器の正式なグローバルディストリビューターであり、Cisco、Juniper、Fortinet、Huaweiなどの主要ネットワークブランドの独立系販売代理店です。世界中にネットワーク機器を販売し、自社および合弁事業向けのソフトウェアを開発しています。",
  paraTwo:
    "CHANGE Networksは、COMMANDO Networks Inc., USAと戦略的パートナーシップを確立し、スイッチ、ルーター、ワイヤレス、光ネットワーク、ミニPCの専門知識を備えたネットワーク機器を提供しています。同社は、世界最高レベルの価格でCOMMANDOネットワーク機器を調達する供給元となっています。",
  paraThree:
    "同社は、新品、ほぼ新品 / 中古品、再生ネットワーク機器を提供しており、COMMANDO、Cisco、Juniper、Fortinetに関する専門知識を持っています。効率的で迅速なサプライチェーンを維持し、1,000万ドル以上の在庫を保有しています。リードタイムは短く、サポートは迅速で、対応時間も速いです。状態に関係なく、100%本物の純正製品のみを取り扱い、標準の1年間保証を提供しています。同社は市場差別化に重点を置き、明確な優位性を持つ製品を選択しています。ROIを向上させ、TCOを削減し、予算を超えない範囲で最高レベルの価値、技術専門知識、サービス、製品の提供を行っています。",
  paraFour:
    "同社は、ドバイ、インド、中国、香港、米国などの戦略的な地域に拠点を持ち、柔軟なビジネス展開を可能にしています。ビジネスの価値と市場差別化を高めるサービスを提供しています。2010年以来、ネットワーク業界に深く関わっています。",
  paraFive:
    "ネットワーキングに関心があるなら、ぜひCHANGEとのビジネス機会を探ってみてください。",
  talkToUs: "お問い合わせ",
  giveUsACall: "お電話ください：+97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "アル・サブカ通り、ユニット6、アル・サブカホテルビル、PO Box #242361、デイラ、ドバイ、UAE",
  sendEmail: "メールを送る",
  emailMessage: "サポートチームに直接連絡すると、迅速に対応します",
  getInTouchWithuS: "お問い合わせ",
  getInTouchWithUsMessage:
    "お客様のビジネス価値を高めるため、ぜひご連絡ください。",
  companyName: "会社名",
  products: "製品",
  price: "価格",
  welcomeMessage: "MultiLangAppへようこそ",
  recommendedProducts: "おすすめ商品",
  productsList: "製品リスト",
  productDescription: "これはサンプル製品の説明です。",
  product: "製品",
};
