export const TEXT_KO = {
  pageNotFound: "페이지를 찾을 수 없음",
  pageNotFoundText: "길을 잃은 것 같아요.",
  takeMeHome: "홈으로 가기",
  goBack: "뒤로 가기",
  back: "뒤로",
  search: "검색",
  confirm: "확인",
  image: "이미지",
  email: "이메일",
  next: "다음",
  reset: "재설정",
  submit: "제출",
  cancel: "취소",
  yes: "예",
  no: "아니요",
  user: "사용자",
  completed: "완료됨",
  name: "이름",
  enterEmail: "이메일 입력",
  selectCountry: "국가 선택",
  selectCountryCode: "국가 코드 선택",
  enterContact: "연락처 입력",
  message: "메시지",
  enterMessage: "메시지 입력",
  contactNo: "연락처",
  country: "국가",
  countryCode: "국가 코드",
  enterCompanyName: "회사명 입력",
  close: "닫기",
  clear: "지우기",
  apply: "적용",
  select: "선택",
  aboutUs: "회사 소개",
  contactUs: "문의하기",
  multiLang: "다국어 지원 앱",
  changeTheme: "테마 변경",
  paraOne:
    "CHANGE Networks는 네트워크 및 소프트웨어 개발 분야에서 전문성을 갖춘 다국적 IT 기업입니다. 이 회사는 COMMANDO 네트워크 장비의 글로벌 공식 유통업체이며 Cisco, Juniper, Fortinet 및 Huawei와 같은 주요 네트워크 브랜드의 독립 리셀러입니다. 전 세계적으로 네트워크 장비를 판매하며, 자체 및 합작 투자 요구 사항을 위한 소프트웨어를 개발합니다.",
  paraTwo:
    "CHANGE Networks는 미국 COMMANDO Networks Inc.와 전략적 파트너십을 체결하여 스위치, 라우터, 무선 네트워크, 광 네트워크 및 미니 PC 분야에서 전문적인 네트워크 장비를 제공합니다. 이 회사는 전 세계적으로 가장 경쟁력 있는 가격으로 COMMANDO 네트워크 장비를 조달하는 강력한 공급망을 보유하고 있습니다.",
  paraThree:
    "이 회사는 새로운 제품, 거의 새 제품 / 중고 및 리퍼비시된 네트워크 장비를 제공합니다. COMMANDO, Cisco, Juniper 및 Fortinet 제품에 대한 전문성을 보유하고 있으며, 1,000만 달러 이상의 재고를 보유하고 있습니다. 공급망이 효율적이고 빠르며, 리드 타임이 짧고, 지원이 신속하며, 응답 시간이 빠릅니다. 제품의 상태와 관계없이 100% 정품만을 취급하며, 기본적으로 1년 보증이 제공됩니다. 이 회사는 시장 차별성이 있는 제품에 집중하여 명확한 경쟁 우위를 확보하고 있으며, 높은 ROI와 낮은 총소유비용(TCO)을 제공합니다. 예산을 초과하지 않으면서도 최고의 가치를 제공하는 기술 전문성과 서비스, 제품 가용성을 보장합니다.",
  paraFour:
    "이 회사는 두바이, 인도, 중국, 홍콩, 미국 등 전략적으로 중요한 지역에서 활동하며 비즈니스 유연성을 제공합니다. 귀사의 비즈니스에 가치를 더하고 시장 차별화를 실현할 수 있도록 지원합니다. 2010년부터 네트워크 업계에서 깊은 경험을 쌓아왔습니다.",
  paraFive:
    "네트워킹 업계에 종사하고 있다면, CHANGE와의 비즈니스 기회를 놓치지 마세요.",
  talkToUs: "문의하기",
  giveUsACall: "+97143523344로 전화 주세요",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "알 사브카 로드, 유닛 6, 알 사브카 호텔 빌딩, PO Box #242361, 데이라, 두바이, UAE",
  sendEmail: "이메일 보내기",
  emailMessage: "신속한 응답을 받으려면 지원팀에 직접 문의하세요",
  getInTouchWithuS: "문의하기",
  getInTouchWithUsMessage:
    "귀사의 비즈니스 가치를 높일 수 있도록 연락드리겠습니다.",
  companyName: "회사명",
  products: "제품",
  price: "가격",
  welcomeMessage: "MultiLangApp에 오신 것을 환영합니다",
  recommendedProducts: "추천 제품",
  productsList: "제품 목록",
  productDescription: "이것은 샘플 제품 설명입니다.",
  product: "제품",
};
