export const TEXT_PT = {
  pageNotFound: "Página Não Encontrada",
  pageNotFoundText: "Parece que você se perdeu no caminho.",
  takeMeHome: "Leve-me para Casa",
  goBack: "Voltar",
  back: "Voltar",
  search: "Pesquisar",
  confirm: "Confirmar",
  image: "Imagem",
  email: "E-mail",
  next: "Próximo",
  reset: "Redefinir",
  submit: "Enviar",
  cancel: "Cancelar",
  yes: "Sim",
  no: "Não",
  user: "Usuário",
  completed: "Concluído",
  name: "Nome",
  enterEmail: "Digite o E-mail",
  selectCountry: "Selecione o País",
  selectCountryCode: "Selecione o Código do País",
  enterContact: "Digite o Número de Contato",
  message: "Mensagem",
  enterMessage: "Digite a Mensagem",
  contactNo: "Número de Contato",
  country: "País",
  countryCode: "Código do País",
  enterCompanyName: "Digite o Nome da Empresa",
  close: "Fechar",
  clear: "Limpar",
  apply: "Aplicar",
  confirm: "Confirmar",
  select: "Selecionar",
  aboutUs: "Sobre Nós",
  contactUs: "Fale Conosco",
  multiLang: "MultiLangCurrApp",
  changeTheme: "Alterar Tema",
  paraOne:
    "CHANGE Networks é uma empresa multinacional de TI com expertise em redes e desenvolvimento de software. A empresa é distribuidora global autorizada dos equipamentos de rede COMMANDO e um dos principais revendedores independentes de grandes marcas de redes como Cisco, Juniper, Fortinet e Huawei. Vende equipamentos de rede em todo o mundo e desenvolve software para suas próprias necessidades internas e de joint ventures.",
  paraTwo:
    "A CHANGE Networks estabeleceu uma parceria estratégica com a COMMANDO Networks Inc., EUA – que oferece equipamentos de rede com expertise em Switches, Roteadores, Redes sem Fio, Redes Ópticas e Mini PCs. A empresa é uma potência na aquisição de equipamentos de rede COMMANDO a um custo incomparável mundialmente.",
  paraThree:
    "A empresa oferece equipamentos de rede novos, seminovos/usados e recondicionados – com expertise em COMMANDO, Cisco, Juniper e Fortinet. Mantém uma cadeia de suprimentos eficiente e rápida, com mais de $10 milhões em estoque. O prazo de entrega é mais curto, o suporte é ágil e o tempo de resposta é rápido. A empresa lida apenas com produtos 100% originais e genuínos, independentemente da condição, com garantia padrão de um ano. Faz escolhas de portfólio mais inteligentes, focando em ofertas com diferenciação de mercado e onde possui uma vantagem forte e clara. A empresa oferece um ROI mais alto e um TCO mais baixo, garantindo o mais alto nível de valor, expertise técnica, serviço e disponibilidade de produtos sem comprometer o orçamento.",
  paraFour:
    "A empresa oferece flexibilidade nos negócios com presença em regiões estratégicas como Dubai, Índia, China, Hong Kong e EUA. Agrega valor e diferenciação de mercado às suas ofertas comerciais. A empresa atua no setor de redes desde 2010.",
  paraFive:
    "Se você trabalha com redes, não perca a oportunidade de explorar negócios com a CHANGE.",
  talkToUs: "Fale Conosco",
  giveUsACall: "Ligue para nós no +97143523344",
  changeNetworksAddressHeading: "CHANGE Networks LLC",
  changeNetworksAddress:
    "  Al Sabkha Road, Unidade Nº 6, Prédio do Hotel Al Sabkha, PO Box #242361 Deira, Dubai, Emirados Árabes Unidos",
  sendEmail: "Enviar E-mail",
  emailMessage:
    "Entre em contato diretamente com nossa equipe de suporte para obter uma resposta rápida",
  getInTouchWithuS: "Entre em Contato Conosco",
  getInTouchWithUsMessage:
    " Teremos o prazer de entrar em contato com você para agregar valor ao seu negócio.",
  companyName: "Nome da Empresa",
  products: "Produtos",
  price: "Preço",
  welcomeMessage: "Bem-vindo ao MultiLangApp",
  recommendedProducts: "Produtos Recomendados",
  productsList: "Lista de Produtos",
  productDescription: "Esta é uma descrição de produto de amostra.",
  product: "Produto",
};
